name:                ghg
version:             0.1.0.0
github:              "jf16688/glossy-haskell-game"
license:             GPL
# author:              "Author name here"
# maintainer:          "example@example.com"
# copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jf16688/glossy-haskell-game#readme>

dependencies:
- base >= 4.7 && < 5
- gloss
- random

library:
  source-dirs: src

executables:
  ghg-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ghg

tests:
  ghg-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ghg
